MAIN_ARDUINO_ADDRESS: 0x01
MAIN_ARDUINO_MESSAGE_LENGTH: 64

ARM_ARDUINO_ADDRESS: 0x02
ARM_ARDUINO_MESSAGE_LENGTH: 64

GPS_ADDRESS: 0x03
GPS_MESSAGE_LENGTH: 64

INS_ADDRESS: 0x04
INS_MESSAGE_LENGTH: 64