MAIN_ARDUINO_ADDRESS: 0x09
MAIN_ARDUINO_MESSAGE_LENGTH: 512

ARM_ARDUINO_ADDRESS: 0x08
ARM_ARDUINO_MESSAGE_LENGTH: 512

GPS_ADDRESS: 0x03
GPS_MESSAGE_LENGTH: 64

INS_ADDRESS: 0x04
INS_MESSAGE_LENGTH: 64